spring:
 application:
  name: "spro-user-service"

server:
 port: 8093

# Actuator Configuration
management:
  info:
    java:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
        
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka

   
# lombok
# open-api-3.0
# spring profiles - dev , qa , prod
# slf4j rolling appender
# jwt-controller (mongo-crud) , okta-controller , ldap-controller

# parent-project pom relationship
# commons-model dependency relationship
# user encryption library
# checkstyle and formatter
# 
